# Generated by Django 4.2.4 on 2023-10-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
